name: simli_client
description: Simli Client is a Flutter package that integrates with the Simli API, enabling real-time, low-latency streaming avatars. Leverages WebRTC for seamless video rendering and peer connections, ideal for virtual assistants and customer service bots.
version: 1.0.0
homepage: https://github.com/jemisgoti/simli-flutter-client
repository: https://github.com/jemisgoti/simli-flutter-client
issue_tracker: https://github.com/jemisgoti/simli-flutter-client/issues
documentation: https://jemisgoti.github.io/simli-flutter-client

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.11.5
  http: ^1.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

screenshots:
  - description: "This screenshot shows the animation in web"
    path: preview/1.gif
  - description: "This screenshot shows avatar selection"
    path: preview/1.png
  - description: "This screenshot shows conversation view"
    path: preview/2.png


# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
